In [3]:
import numpy as np

In [9]:
x1 = np.array([[1,2],[3,4]])
x2 = np.array([[5,6],[8,10]])
print(x1-x2)
np.sum(x1 - x2,axis=1)

[[-4 -4]
 [-5 -6]]


array([ -8, -11])

In [14]:
x = np.array([3, 4, 2, 1])

In [54]:
np.partition(x,1)

array([1, 2, 4, 3])

In [53]:
np.argpartition(x,1)

array([3, 2, 1, 0], dtype=int64)

In [64]:
x = np.array([[1,2],[3,4]])

In [79]:
np.sum(x, axis=0)

array([4, 6])

In [76]:
b = np.array([1,2])

In [78]:
np.sum(x + b, axis=0)

array([ 6, 10])

In [84]:
np.dot(x, x) == x @ x

array([[ True,  True],
       [ True,  True]])

In [86]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [55]:
import numpy as np

In [58]:
2/6 * np.log2(1/3) + 4/6 * np.log2(2/3)

-0.9182958340544896

In [53]:
8/25

0.32

In [59]:
import pandas as pd


In [65]:
age = [12, 23, 13]
name = ['aravind', 'anand', 'sudha']

df = pd.DataFrame(np.array([age, name]).T, columns=['age', 'name'])

In [66]:
df

age     name
0  12  aravind
1  23    anand
2  13    sudha

In [5]:
import numpy as np

In [15]:
def predict_class(y):
  return np.unique(y, return_counts=True)

In [3]:
y = [5, 8, 9, 5, 0, 0, 1, 7, 6, 9, 2, 4, 5, 2, 4, 2, 4, 7, 7, 9, 1, 7, 0, 6, 9, 9, 7, 6, 9, 1, 0, 1, 8, 8, 3, 9, 8, 7, 3, 6, 5, 1, 9, 3, 4, 8, 1, 4, 0, 3, 9, 2, 0, 4, 9, 2, 7, 7, 9, 8, 6, 9, 3, 7, 7, 4, 5, 9, 3, 6, 8, 0, 2, 7, 7, 9, 7, 3, 0, 8, 7, 7, 1, 1, 3, 0, 8, 6, 4, 5, 6, 2, 5, 7, 8, 4, 4, 7, 7, 4, 9, 0, 2, 0, 7, 1, 7, 9, 8, 4, 0, 1, 9, 8, 2, 3, 1, 2, 7, 2, 6, 0, 9, 2, 6, 6, 2, 7, 7, 0, 6, 5, 1, 4, 6, 0, 6, 5, 1, 2, 1, 5, 4, 0, 7, 8, 9, 5, 7, 0, 9, 3, 9, 1, 4, 4, 6, 8, 8, 9, 2, 7, 5, 5, 4, 5, 8, 5, 8, 1, 1, 8, 7, 0, 3, 4, 2, 0, 3, 5, 1, 2, 4, 3, 0, 6, 0, 7, 2, 8, 3, 0, 8, 4, 2, 9, 0, 3, 8, 1, 4, 3, 3, 6, 7, 3, 5, 3, 2, 4, 4, 0, 3, 3, 8, 3, 5, 6, 7, 5, 1, 7, 0, 2, 8, 2, 1, 4, 0, 4, 1, 7, 3, 1, 6, 6, 9, 6, 9, 6, 0, 0, 2, 9, 6, 0, 6, 7, 0, 3, 9, 0, 3, 4, 7, 5, 3, 8, 8, 0, 6, 7, 9, 5, 4, 9, 5, 2, 5, 6, 6, 8, 7, 7, 7, 2, 6, 0, 5, 2, 1, 8, 5, 9, 4, 9, 1, 2, 0, 4, 7, 0, 6, 2, 4, 3, 6, 7, 6, 3, 0, 6, 4, 7, 6, 2, 9, 5, 9, 9, 9, 8, 6, 4, 2, 9, 4, 0, 0, 3, 4, 9, 3, 9, 1, 2, 5, 4, 0, 8, 2, 3, 9, 9, 4, 4, 8, 2, 1, 6, 3, 8, 9, 7, 0, 5, 2, 2, 8, 5, 0, 5, 9, 8, 6, 6, 0, 4, 7, 3, 0, 1, 6, 0, 6, 1, 6, 4, 2, 5, 4, 6, 2, 9, 2, 7, 5, 0, 7, 8, 8, 8, 0, 7, 2, 0, 7, 1, 1, 9, 5, 1, 5, 9, 6, 4, 9, 8, 7, 5, 1, 8, 0, 5, 3, 9, 0, 4, 8, 6, 2, 4, 3, 2, 0, 0, 4, 2, 5, 0, 0, 3, 8, 5, 3, 1, 4, 7, 3, 2, 2, 2, 6, 6, 0, 1, 5, 6, 5, 8, 8, 5, 5, 7, 5, 9, 1, 3, 9, 3, 3, 3, 6, 1, 3, 0, 5, 0, 5, 2, 7, 6, 4, 0, 2, 4, 8, 7, 6, 7, 7, 1, 7, 7, 3, 8, 3, 0, 6, 3, 0, 6, 5, 9, 6, 4, 6, 6, 2, 2, 4, 1, 2, 3, 9, 3, 6, 7, 0, 3, 3, 6, 8, 6, 5, 1, 3, 2, 6, 3, 6, 7, 2, 8, 0, 1, 8, 6, 0, 0, 1, 2, 7, 7, 4, 4, 0, 1, 0, 8, 5, 6, 2, 5, 4, 3, 0, 6, 2, 1, 9, 4, 4, 0, 9, 8, 7, 7, 6, 1, 7, 2, 4, 5, 6, 7, 2, 0, 5, 2, 7, 9, 9, 7, 1, 1, 4, 6, 5, 6, 4, 1, 1, 5, 1, 2, 6, 2, 3, 3, 2, 3, 0, 0, 1, 5, 0, 5, 8, 8, 0, 0, 0, 9, 8, 5, 9, 3, 4, 0, 9, 8, 6, 3, 9, 9, 0, 8, 1, 6, 6, 1, 3, 7, 3, 2, 3, 0, 2, 8, 2, 9, 0, 1, 3, 9, 4, 8, 8, 8, 2, 8, 6, 4, 9, 0, 5, 5, 6, 1, 7, 6, 5, 7, 1, 9, 7, 5, 6, 7, 6, 7, 5, 6, 8, 7, 4, 2, 4, 0, 0, 3, 5, 9, 0, 3
, 6, 5, 1, 1, 8, 4, 7, 0, 1, 7, 1, 5, 4, 5, 6, 2, 5, 3, 9, 3, 9, 5, 1, 9, 7, 7, 0, 8, 6, 1, 2, 0, 4, 4, 6, 1, 0, 9, 4, 9, 3, 0, 5, 1, 1, 9, 6, 0, 2, 8, 3, 7, 2, 5, 6, 0, 4, 2, 3, 1, 0, 5, 7, 0, 2, 2, 0, 9, 5, 1, 1, 6, 3, 2, 1, 1, 2, 7, 5, 2, 9, 4, 7, 3, 5, 0, 2, 1, 4, 9, 4, 6, 9, 3, 8, 8, 7, 1, 8, 7, 8, 9, 2, 2, 5, 5, 3, 5, 9, 2, 7, 4, 1, 6, 9, 8, 1, 8, 1, 6, 2, 6, 1, 8, 3, 7, 0, 7, 0, 0, 7, 3, 9, 5, 2, 5, 1, 2, 5, 3, 3, 6, 1, 8, 1, 8, 6, 4, 6, 9, 5, 4, 7, 2, 0, 2, 0, 5, 9, 4, 1, 4, 5, 2, 9, 3, 1, 5, 1, 1, 7, 1, 2, 6, 0, 7, 7, 4, 3, 2, 7, 8, 5, 2, 4, 9, 2, 2, 3, 5, 9, 6, 4, 9, 0, 2, 8, 3, 7, 3, 9, 2, 3, 8, 8, 0, 2, 6, 8, 3, 6, 4, 9, 7, 6, 3, 2, 9, 1, 5, 5, 6, 9, 4, 6, 7, 8, 5, 7, 2, 5, 3, 4, 5, 9, 2, 4, 0, 3, 5, 2, 6, 2, 8, 0, 2, 6, 4, 8, 4, 3, 4, 9, 8, 3, 5, 2, 0, 7, 9, 8, 1, 4, 6, 1, 6, 9, 3, 4, 3, 7, 3, 8, 3, 4, 4, 4, 6, 3, 0, 4, 6, 4, 9, 3, 0, 6, 2, 9, 2, 9, 0, 1, 2, 4, 6, 0, 6, 0, 0, 2, 6, 4, 1, 5, 8, 2, 2, 6, 5, 1, 2, 7, 6, 7, 4, 5, 7, 2, 3, 7, 4, 1, 5, 8, 3, 1, 0, 8, 8, 4, 4, 2, 6]

In [21]:
classes, counts = predict_class(y)
print(classes, counts)
print(classes[np.argmax(counts)])

[0 1 2 3 4 5 6 7 8 9] [111  92 110  97  99  96 110 102  87  96]
0


In [22]:
import numpy as np
def gini_index(dict):
    total = sum(dict.values())
    total_p = 0
    for each in dict.keys():
        p = dict.values[each]/total
        total_p += p * (1 - p)
        
    return total_p

In [1]:
import numpy as np

a = np.array([1,2,4,5,6])
a.size

5

In [2]:
w0 = 6
w1 = 5
n = 200
X = 10 * np.random.rand(n,)

In [6]:
a = w1 * X + np.random.rand(n,)

In [10]:
a

array([26.36475508, 42.03810724, 26.73158014,  3.53675557, 37.34411284,
       47.40244807, 30.89216605, 18.14911322, 20.25168595, 17.93808319,
        4.39058325, 41.63258096, 10.0529608 ,  1.05125474, 35.9698247 ,
       14.00300973,  8.63918902,  8.80672372, 19.59656848,  4.40162025,
       47.37101795, 26.54924402, 34.65146674, 22.08797487, 40.60794315,
       49.11763525, 13.53969531, 38.98540754, 11.26959091, 13.66781742,
        3.60114716,  7.59970809,  3.36905557, 42.00401065, 11.03426405,
       43.70228624, 15.23434045, 34.71409563, 40.36139969,  1.91617808,
       35.86033589,  5.96953808, 40.40511379,  0.68052054, 32.08843414,
       35.91773533, 21.655054  , 33.28865365, 42.56699156, 42.83366649,
       21.79082644, 22.60960029, 19.89520646, 16.41353027,  6.12830956,
        2.82179936, 30.58245942, 12.96436881, 12.92575958, 47.23869994,
       22.19380457, 30.19315188,  6.9296136 , 15.92425534, 28.98527126,
        2.23910908,  1.56904026, 24.35351008,  4.4003808 , 10.71

In [15]:
(a + w0 - w0) - a

array([-3.55271368e-15,  0.00000000e+00,  0.00000000e+00, -8.88178420e-16,
        0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  0.00000000e+00,  8.88178420e-16,  0.00000000e+00,
        0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  0.00000000e+00,  0.00000000e+00, -8.88178420e-16,
        0.00000000e+00,  3.55271368e-15,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  1.77635684e-15,  4.44089210e-16,  8.88178420e-16,
       -8.88178420e-16,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  2.22044605e-16,
        0.00000000e+00,  8.88178420e-16,  0.00000000e+00,  3.33066907e-16,
        0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  

In [36]:
X = np.array([[1,2],[1,3]])
w = np.array([0.1,0.2])
y = np.array([1,0])

In [40]:
def linear_combination(X, w):
    return X @ w

In [41]:
def sigmoid(z):
    return 1 / (1 + np.exp(-z))

In [42]:
def activation(X, w):
    return sigmoid(linear_combination(X, w))

In [43]:
def calculate_gradient(X, y, w, reg_rate=0):
    return X.T @ (activation(X, w) - y) + reg_rate * w

In [44]:
calculate_gradient(X, y, w)

array([0.2906471 , 1.24948198])

In [53]:
y = np.array([ 1, 0, 0, 1, 0, 0, 0, 1, 1 ])
y_hat = np.array([0.9,0.3,0.25,0.88,0.1,0.1,0.6,0.9,0.75])

In [54]:
y @ np.log(y_hat) + (1 - y) @ np.log(1 -y_hat)

-2.3976052548576394