In [1]:
import numpy as np

#### Element-by-element

Using a normal operation between arrays does element-by-element operation.  For example, matrix multiplication cannot be done using normal multiplication operator.

In [2]:
A = 3 * np.ones((2,2)) #3 is multiplied with every element in the array
B = 6 * np.ones((2,2)) #6 is multiplied with every element in the array
A * B

array([[18., 18.],
       [18., 18.]])

#### Is it matmul or dot?

Both will give same result for a 2D array, but 3D and above the results are different.  In the case of 2D arrays, matmul should be preferred over dot operation.

In [3]:
np.matmul(A, B)

array([[36., 36.],
       [36., 36.]])

In [4]:
A @ B

array([[36., 36.],
       [36., 36.]])

In [5]:
np.dot(A, B) #same as matrix multiplication for 2 x 2 arrays.

array([[36., 36.],
       [36., 36.]])

Between matmul and dot, always prefer to use matmul

In [6]:
#matrix multiplication and dot product are not same for higher dimensional arrays (more than 2D)
A = np.random.rand(2,3,3)
B = np.random.rand(2,3,3)
print(np.dot(A, B).shape)
print((A @ B).shape)

(2, 3, 2, 3)
(2, 3, 3)


#### Broadcasting an entire row?

The entire first (and only) row of A, is entirely broadcast during multiplication operation with B.  This works only since the number of columns in A and B are equal.

In [7]:
A = 3 * np.ones((1,2))
B = 6 *np.ones((3,2))
A * B

array([[18., 18.],
       [18., 18.],
       [18., 18.]])

#### Broadcasting an entire column?

The entire first (and only) column of A, is entirely broadcast during multiplication operation with B.  This works only since the number of rows in A and B are equal.

In [8]:
A = 3 * np.ones((2,1))
B = 6 *np.ones((2,3))
A * B

array([[18., 18., 18.],
       [18., 18., 18.]])

#### What is np.argmax function?

Finds the index of the maximum in a row/column of given array

In [9]:
A = 10 * np.random.random((7, 7))
print(A)

[[0.79810013 8.36760337 5.3643186  1.30690837 7.10767716 6.61642046
  8.93274459]
 [9.15502014 5.35401857 2.18344306 3.70083678 7.68736931 8.72585365
  9.01619659]
 [1.10400585 3.03714355 4.67866116 1.0230112  5.31199255 9.1228265
  0.75589361]
 [6.71714011 5.13280581 9.64117978 9.82871591 4.04428512 8.86553752
  3.53632162]
 [3.35121428 6.1667634  0.5325857  6.52655115 7.99855417 2.47634102
  1.72361607]
 [8.53953555 6.61167142 2.24199903 6.40111621 7.48004394 4.57480373
  3.41910018]
 [0.56801848 5.55718508 6.59990463 8.8860317  3.25468349 5.92788591
  5.8986734 ]]


In [10]:
np.argmax(A) #Flattens the array before returning the index of the max.element.

24

In [11]:
np.argmax(A, axis=0) #Finds index of the max. element down each column.

array([1, 0, 3, 3, 4, 2, 1], dtype=int64)

In [12]:
np.argmax(A, axis=1) #Finds index of the max. element across each row.

array([6, 0, 5, 3, 4, 0, 3], dtype=int64)

#### Ok, so, how does this axis parameter work?

For example, using axis parameter with np.sum, sums up all elements of the array down the column when axis=0, and across row when axis=1

In [13]:
A = np.random.randint(1, 10, size=12).reshape(3,4)
print(A)

[[5 6 8 9]
 [6 6 7 8]
 [3 6 8 6]]


In [14]:
np.sum(A, axis=0) #sums down the column

array([14, 18, 23, 23])

In [15]:
np.sum(A, axis=1) #sums across the row

array([28, 27, 23])

#### Stack or concatentate?

Both can achieve the same result, but while using concatenate parameter must a tuple, and axis must be specified.  Thus, concatenating along 0th axis stacks vertically, and along 1st axis stacks horizontally.

In [16]:
A = np.ones((2,2))
B = 2*np.ones((2,2))
A_B = np.hstack((A,B))
# A_B = np.concatenate((A, B), axis=1) # same as above
print(A_B)

[[1. 1. 2. 2.]
 [1. 1. 2. 2.]]


In [17]:
C = 3*np.ones((2,2))
D = 4*np.ones((2,2))
C_D = np.hstack((C,D))
# C_D = np.concatenate((C, D), axis=1) # same as above
print(C_D)

[[3. 3. 4. 4.]
 [3. 3. 4. 4.]]


In [18]:
T = np.vstack((A_B,C_D))
# T = np.concatenate((A_B, C_D), axis=0) # same as above
print(T)

[[1. 1. 2. 2.]
 [1. 1. 2. 2.]
 [3. 3. 4. 4.]
 [3. 3. 4. 4.]]
