In [3]:
import numpy as np

In [9]:
x1 = np.array([[1,2],[3,4]])
x2 = np.array([[5,6],[8,10]])
print(x1-x2)
np.sum(x1 - x2,axis=1)

[[-4 -4]
 [-5 -6]]


array([ -8, -11])

In [14]:
x = np.array([3, 4, 2, 1])

In [54]:
np.partition(x,1)

array([1, 2, 4, 3])

In [53]:
np.argpartition(x,1)

array([3, 2, 1, 0], dtype=int64)

In [64]:
x = np.array([[1,2],[3,4]])

In [79]:
np.sum(x, axis=0)

array([4, 6])

In [76]:
b = np.array([1,2])

In [78]:
np.sum(x + b, axis=0)

array([ 6, 10])

In [84]:
np.dot(x, x) == x @ x

array([[ True,  True],
       [ True,  True]])

In [86]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])